name: Test project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  solana_version: '1.14.9'
  anchor_version: '0.21.0'

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        case:
          [
            'npm run test:swap',
            'npm run test:multiple-swap',
            'npm run test:cross',
            'npm run test:cross-both-side',
            'npm run test:liquidity-gap',
            'npm run test:simulate-swap',
            'npm run test:reversed',
            'npm run test:position',
            'npm run test:math',
            'npm run test:withdraw',
            'npm run test:withdraw-staker',
            'npm run test:position-list',
            'npm run test:claim',
            'npm run test:random',
            'npm run test:simulate-claim-amount',
            'npm run test:math-staker',
            'npm run test:cu',
            'npm run test:init-both',
            'npm run test:change-protocol-fee',
            'npm run test:tickmap',
            'npm run test:change-fee-receiver',
            'npm run test:whole-liquidity',
            'npm run test:position-change',
            'npm run test:protocol-fee',
            'npm run test:target',
            'npm run test:slippage',
            'npm run test:position-slippage',
            'npm run test:fee-tier',
            'npm run test:big-swap',
            'npm run test:create',
            'npm run test:stake',
            'npm run test:multicall',
            'npm run test:oracle',
            'npm run test:limits',
            'npm run test:compare',
            'npm run test:max-tick-cross',
            'npm run test:close-stake',
            'cargo test',
            'npm run test:referral-default',
            'npm run test:referral-all',
            'npm run test:referral-none',
            'npm run test:referral-jupiter',
            'cargo test --features "all"',
            'cargo test --features "none"',
            'cargo test --features "jupiter"'
          ]
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: |
          echo "${{ matrix.case }}"
      - uses: actions/cache@v2
        name: Cache Cargo registry + index
        id: cache-anchor
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ runner.os }}-v0000-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v2
        name: Cache Solana Tool Suite
        id: cache-solana
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-v0000-${{ env.solana_version }}
      - uses: actions/cache@v2
        name: Cache target folder
        id: cache-programs
        with:
          path: |
            ./target
          key: solana-${{ runner.os }}-v0000-${{ hashFiles('**/programs/**/*.rs') }}-${{ hashFiles('**/programs/**/*.toml') }}
      - uses: actions/cache@v2
        name: Cache Node Modules
        id: cache-node-modules
        with:
          path: |
            ~/.npm/
            ./node_modules
          key: npm-${{ runner.os }}-v0000-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: install global mocha
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          npm install -g mocha
          npm install -g ts-mocha
          npm install -g typescript
          npm install -g @project-serum/anchor
          ts-mocha -h
      - name: install essential
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev
      - name: install solana
        if: steps.cache-solana.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.solana_version }}/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
      - name: setup solana
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          solana-keygen new -o "$HOME/.config/solana/id.json" --no-passphrase --silent
      - name: install Anchor
        if: steps.cache-anchor.outputs.cache-hit != 'true'
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          cargo install --git https://github.com/project-serum/anchor --tag v${{ env.anchor_version }}  anchor-cli --locked
      - name: build programs
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          anchor build
      - name: install
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          npm install
      - name: build invariant sdk & staker sdk
        run: |
          npm run build:all
      - name: test
        run: |
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          ${{ matrix.case }}
